[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
cli-log = "2.1.0"
crossterm = "0.29.0"
ratatui = "0.30.0"
renet_netcode = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
postcard = "1.0"
